CREATE TABLE locks (
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	ip VARCHAR(16) NOT NULL DEFAULT '',
	time INT NOT NULL DEFAULT 0,
	action VARCHAR(16) NOT NULL DEFAULT '',
	num INT NOT NULL DEFAULT 0
);
